### PR TITLE
Fix call to http from https

### PR DESCRIPTION
**Pull request by Victory**
github.io is on https so the requests should be on https.

### CODE REVIEW

**Comment by sparticle999** [comment]
Thank You Victory

**Comment by sparticle999** [comment]
But what does this do?

**Comment by Victory** [comment]
Hmm... That's a good but broad question. Addressing just the game adding the Scope object makes it harder for someone to open up their browser's debugger and just set a value for the winning variable. In terms of coding best practices the change makes it so only the functions and variables you wish to expose are made easily accessible. 

As it stands now its still kinda easy to cheat, so if that is what you are interested in we could make it less easy then we could see more of the benefits of this pattern.

Think about if someone put the following into their debugger:

```
 for  (var ii = 0; ii < 1000000; ii++) { gainOre() }
```

or 

```
for  (var ii = 0; ii < 1000000; ii++) { Game.gainOre() }
```

**Comment by sparticle999** [comment]
Thank you for the clarification. As always, I appreciate contributions.

**Pull request merged**
